version: '3'

services:
  whoiami:
    container_name: whoami
    build:  
      context: ./

    ports: 
      - "3000:80"
      
networks:
  default:
    external:
      name: nginx-network
#docker-compose down -v && docker-compose up --build -d