version: '3'

services:
  proxy:
    build:
      context: ./
      dockerfile: Dockerfile
    ports: 
      - "80:80"    
      
networks:
  default:
    external:
      name: nginx-network
#docker-compose down -v && docker-compose up --build -d